version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '08:00'
      timezone: 'Europe/London'
    reviewers:
      - 'koenoe'
    labels:
      - 'npm'
      - 'dependencies'
    open-pull-requests-limit: 10
    groups:
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      next:
        patterns:
          - 'next'
          - '@next/*'
          - '@opennextjs/*'
      aws-sdk:
        patterns:
          - '@aws-sdk/*'
      hono:
        patterns:
          - 'hono'
          - '@hono/*'
      tailwind:
        patterns:
          - 'tailwindcss'
          - 'tailwind-*'
          - '@tailwindcss/*'
      types:
        patterns:
          - '@types/*'
        exclude-patterns:
          - '@types/react'
          - '@types/react-*'
          - '@types/node'
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
